// Assignment 8/React/src/App.js
import logo from './logo.svg';
import './App.css';

import axios from "axios";
import React from "react";

function App() {
  const [contacts, setContacts] = React.useState(null);

  React.useEffect(() => {
    axios.get("http://localhost:3000/contact").then((response) => setContacts(response.data));
  }, []);

  if (!contacts) return null;

  return (
    <div>
      <h1>Contacts</h1>
      <ul>
        {contacts.map(contact => {
          return (
            <li>{contact.firstname} {contact.lastname}<br/>{contact.email}</li>
          )
        })}
      </ul>
    </div>
  );
}

export default App;

// Assignment 8/Vue/src/App.vue
<template>
  <h1>Contacts</h1>
  <ul v-for="contact of contacts" :key="contact._id">
    <li>{{ contact.firstname }} {{ contact.lastname }}<br>{{ contact.email }}</li>
  </ul>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      contacts: [],
      errors: []
    }
  },

  async created() {
    try {
      const response = await axios.get(`http://localhost:3000/contact`);
      this.contacts = response.data;
      console.log(response.data);
    } catch (err) {
        this.errors.push(err);
    }
  }
}
</script>

<style>
</style>
